name: evently_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_native_splash: 2.4.4
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  introduction_screen: ^3.1.17
  animated_toggle_switch: ^0.8.4
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  adaptive_dialog: ^2.4.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
