// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVNSP5hNMZHpzxuAeHlTQbL2y-nlKbMg',
    appId: '1:386810576746:android:992f6b34365277d2f06f13',
    messagingSenderId: '386810576746',
    projectId: 'evently-app-f4b96',
    storageBucket: 'evently-app-f4b96.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYPkDZBlqNo-s2Dam2ryhfZaO-330sFkU',
    appId: '1:386810576746:web:5fd7ffb2a71ea8d4f06f13',
    messagingSenderId: '386810576746',
    projectId: 'evently-app-f4b96',
    authDomain: 'evently-app-f4b96.firebaseapp.com',
    storageBucket: 'evently-app-f4b96.firebasestorage.app',
    measurementId: 'G-941JEWFJ54',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY0dmwP-vfbsg8RPF6y9e5HjGDdXfGuKg',
    appId: '1:386810576746:ios:b13656fa63dc7db1f06f13',
    messagingSenderId: '386810576746',
    projectId: 'evently-app-f4b96',
    storageBucket: 'evently-app-f4b96.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

}